image: node:16.0
pipelines:
 branches:
  develop:
  - step:
     name: Deploy to master
     script:
        - ssh -i ~/.ssh/id_rsa root@52.65.237.239 'cd /var/www/dev/dev.app.ecommify.io'
        - ssh -i ~/.ssh/id_rsa root@52.65.237.239 'git pull origin develop'
        - ssh -i ~/.ssh/id_rsa root@52.65.237.239 'npm install --cache'
        - ssh -i ~/.ssh/id_rsa root@52.65.237.239 'CI= npm run-script build-dev'
        - ssh -i ~/.ssh/id_rsa root@52.65.237.239 'cd /var/www/dev/dev.app.ecommify.io'
        - ssh -i ~/.ssh/id_rsa root@52.65.237.239 'cp htaccess dist/callbreak-CMS/.htaccess'
        - ssh -i ~/.ssh/id_rsa root@52.65.237.239 'ls dist/callbreak-CMS/.htaccess'
        - ssh -i ~/.ssh/id_rsa root@52.65.237.239 'if test -f "dist/callbreak-CMS/.htaccess"; then echo "exist";rm -rf build_live; mv dist build_live; else echo "not working"; fi'