image: node:16
image: node:16.0
pipelines:
 branches:
  develop:
  - step:
     name: Deploy to master
     script:
        - cd /var/www/dev/dev.app.ecommify.io
        - git pull origin develop
        - npm install --cache
        - CI= npm run-script build-dev
        - cd /var/www/dev/dev.app.ecommify.io
        - cp htaccess dist/callbreak-CMS/.htaccess
        - ls dist/callbreak-CMS/.htaccess
        - if test -f "dist/callbreak-CMS/.htaccess"; then echo "exist";rm -rf build_live; mv dist build_live; else echo "not working"; fi