image: atlassian/default-image:3
pipelines:
 branches:
  develop:
  - step:
        script:
          - pipe: atlassian/ssh-run:0.4.1
            variables:
              SSH_USER: 'root'
              MODE: 'command'
              SERVER: '52.65.237.239'
              COMMAND: 'cd /var/www/dev/dev.app.ecommify.io && curl ifconfig.io && bash  script.sh'
