pipelines:
 branches:
  develop:
  - step:
        script:
          - pipe: atlassian/ssh-run:0.4.1
            variables:
              SSH_USER: 'root'
              MODE: 'command'
              SERVER: '52.65.237.239'
              COMMAND: 'cd /var/www/dev/dev.app.ecommify.io && git pull origin develop && npm install --cache && CI= npm run-script build-dev && cp htaccess dist/ecommify/.htaccess && ls dist/ecommify/.htaccess && if test -f "dist/ecommify/index.html"; then echo "exist";rm -rf build_live; mv dist build_live; else echo "not working"; fi'
