image: node:16
pipelines:
  default:
    - step:
        name: Deploy to EC2
        script:
          - apt-get update && apt-get install rsync -y
          - echo "Installing Angular CLI"
          - sudo npm install -g @angular/cli
          - echo "Building Angular application"
          - ng build
          - echo "Copying files to EC2 instance"
          - rsync -avzhe ssh dist/* root@3.27.77.218:/var/www/dev/dev.app.ecommify.io
