image: node:14.16.0
pipelines:
  branches:
    develop:
      - step:
         name: Deploy to EC2
         script:
          - ng build 
          - scp -r dist/** root@3.27.77.218:/var/www/dev/dev.app.ecommify.io
