image: node:16
pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - node
        script:
          - npm install 
          - npm run build-dev
        artifacts:
          - build/**
    - step:
        name: Deploy artifacts using SCP to dev
        script:
          - pipe: atlassian/scp-deploy:0.3.3
            variables:
              USER: 'root'
              SERVER: '52.65.237.239'
              REMOTE_PATH: '/var/www/dev/dev.app.ecommify.io'
              LOCAL_PATH: 'build/*'
